//USER REGISTRATION
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

//USER LOGIN
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

//USER LOGOUT
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

//USER PROFILE
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

//USER UPDATE
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

// FETCH USERS
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'CREATE_USERS_FAIL';

//TREE

export const CREATE_TREE_REQUEST = 'CREATE_TREE_REQUEST';
export const CREATE_TREE_SUCCESS = 'CREATE_TREE_SUCCESS';
export const CREATE_TREE_FAIL = 'CREATE_TREE_FAIL';

// FETCH BOOKS
export const FETCH_TREE_REQUEST = 'FETCH_TREE_REQUEST';
export const FETCH_TREE_SUCCESS = 'FETCH_TREE_SUCCESS';
export const FETCH_TREE_FAIL = 'CREATE_TREE_FAIL';

//DELETE BOOKS
export const DELETE_TREE_REQUEST = 'DELETE_TREE_REQUEST';
export const DELETE_TREE_SUCCESS = 'DELETE_TREE_SUCCESS';
export const DELETE_TREE_FAIL = 'DELETE_TREE_FAIL';

//BOOK DETAILS
export const TREE_DETAIL_REQUEST = 'TREE_DETAIL_REQUEST';
export const TREE_DETAIL_SUCCESS = 'TREE_DETAIL_SUCCESS';
export const TREE_DETAIL_FAIL = 'TREE_DETAIL_FAIL';

//UPDATE BOOKS
export const TREE_UPDATE_REQUEST = 'TREE_UPDATE_REQUEST';
export const TREE_UPDATE_SUCCESS = 'TREE_UPDATE_SUCCESS';
export const TREE_UPDATE_FAIL = 'TREE_UPDATE_FAIL';